<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB5DeE6X\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB5DeE6X/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerB5DeE6X.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerB5DeE6X\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerB5DeE6X\App_KernelDevDebugContainer([
    'container.build_hash' => 'B5DeE6X',
    'container.build_id' => 'ed17dd06',
    'container.build_time' => 1764870144,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB5DeE6X');
